### ISSUE TITLE
Add flag to filter double counts during extraction

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/mibi-bin-tools#11]
A request from Mike, we should add an option to the extract_bin_file function that allows the user to discard data from TOF cycles with double/multiple hits.

**Comment by ackagel** [comment]
discard as in remove the extra hits, or fully black out the pixel? I assume the former.

**Comment by ngreenwald** [comment]
Yeah, this is just in the context of computing median pulse heights. Wasn't clear from my description.
