### ISSUE TITLE
MPH helper function

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/mibi-bin-tools#19]
I wrote the following helper function to compute the MPH
```
import pandas as pd
def compute_pulse_height(base_dir, bin_file_prefix, mass=98, mass_start=97.5, mass_stop=98.5):
    # construct panel
    panel = pd.DataFrame([{
        'Mass': int(mass),
        'Target': 'Mo98',
        'Start': mass_start,
        'Stop': mass_stop,
    }])
    _, intensities, pulse_counts = bin_files.get_histograms_per_tof(base_dir, bin_file_prefix, 'Mo98', panel)

    int_bin = np.cumsum(intensities) / intensities.sum()
    median = (np.abs(int_bin - 0.5)).argmin()
    return median
```

Do you want to use this method going forward to compute, or is the plan to fix the other version that you have in the repo?

Also, what is the 'target' and 'Mass' columns used for in the panel when extracting median pulse height? Are they relevant, or do we just need the start and stop for the integration window?

**Comment by ackagel** [comment]
the `median_height_vs_mean_pp` currently uses this work around for the median (see line 388 of `bin_files.py`).  I can try fixing the sorting version at some point.

I'm pretty sure the target field is only used for naming the tiffs from the extraction function; honestly, it's another instance where having a Panel dataclass would solve some of those issues.

**Comment by ngreenwald** [comment]
Last thing before dev is ready to be merged into main: It would be nice to have the above function included. I took a look at the functions it calls, and it seems like there's some redundancy between `get_histograms_per_tof`, `median_height_vs_mean_pp`, and this one if I added it in. Do you have a preference for how to organize all of this?

IMO having one python function that calls `c_extract_histograms` makes sense, and then have the others call that if they need it. However, I'm not sure about nested calls to `_fill_fov_metadata`, which I'm guessing is why you have them separated?
