### ISSUE TITLE
Median pulse height count array return process is inherently slow

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/mibi-bin-tools#58]
**Is your feature request related to a problem? Please describe.**

The pulse height extraction process has been the largest bottleneck in the watcher pipeline by miles. While the actual process is very similar to `.bin` file extraction, the main difference is the median pulse height extraction has to return three arrays back to Python. The conversion process between Cython and Python can be very slow if the arrays are large.

**Describe the solution you'd like**

A couple of options here:

1. Let's first see if there's any way we can speed up the return process. We could look into different options for representing the arrays.
2. If that fails, as @ngreenwald, we could return a smaller subsetted array. The median will not be as precise but still acceptable.

**Comment by alex-l-kong** [comment]
One thing to note is that it's a couple outlier channels that are causing the significant bottleneck here because they are extremely bright, requiring the conversions of arrays with massive values from Cython to Python. Specifically, the problematic channels are:

- Au (mass 197)
- chan_39 (mass 39)

It's looking like we'll have to go with option 2 since there's no real way to stop the conversion from happening from Cython to Python. However, I'm hesitant to implement the array subsetting method on all the masses when the vast majority of them are not problematic. @ngreenwald what do you think?

**Comment by ngreenwald** [comment]
How long does it take to calculate MPH for 
1) just moly 92
2) just CD45
3) the entire panel
4) the entire panel except for the three you listed above?

Pick like 10 random bin files and plot the times.

**Comment by alex-l-kong** [comment]
@ngreenwald looks like this repo was not up-to-date on most computers. I've ensured that 0.2.10 has been installed, and `toffy_env` is using Python 3.9 on the machines, and it looks like now it's outputting consistent times across channels for a FOV. For small FOVs, this can be as short as 2 seconds per mass. Larger FOVs, however, do need 30 seconds or even more per mass.

I've done a few timing tests and narrowed down the problem to the way this loop gets called repeatedly per mass: https://github.com/angelolab/mibi-bin-tools/blob/main/src/mibi_bin_tools/_extract_bin.pyx#L215-L234. The time scales up linearly depending on the total number of channels to extract. Which will be a problem even if extraction of a single mass takes 30 seconds (30 s/mass * 40 masses = 1200 s = 20 mins).

The best way around this would be to compute the metrics across all masses at once to avoid needlessly calling the same loop. This, however, will be a significant rewrite. Extremely rough design doc-ing here:

1. The underlying data structure of `widths`, `intensities`, and `pulse_counts` will need to change, since they're currently initialized to hold data from just one mass.
2. We'd have to pass the time of flight ranges for all masses, not just the one in question
3. Related to 2, this line (https://github.com/angelolab/mibi-bin-tools/blob/main/src/mibi_bin_tools/_extract_bin.pyx#L229) will need to change to ensure all time of flight ranges are accounted for, and the correct masses get their counts updated.
4. This function also needs to support single mass extraction, since the mph plotting only extracts a single mass (98 I believe).
5. Any function that calls `get_median_pulse_height` in `toffy` will need to change, since the return will include the counts of all the masses at once, not just for a single mass. Functions would include `toffy.normalize.write_mph_per_mass`, as well as its corresponding watcher function.

@jranek let me know if you have any ideas as well, since you've worked with this function for the deconv project.

**Comment by ngreenwald** [comment]
After updating the repo and redoing the timing, how does the MPH calculation timing compare to channel extraction? Is it still the case that MPH computation per channel is much longer than tiff extraction?

**Comment by jranek** [comment]
Do you think you could use the functions I sent you the other day @alex-l-kong? You can pass in a min and max mass channel of interest, convert to TOF, discretize TOF into appropriately sized time bins, and output the pulse counts, intensities, and widths for all mass channels. The code supports extracting this information for a single mass channel (-0.5, mass, 0.5) or a mass range.

**Comment by alex-l-kong** [comment]
@ngreenwald yes, the total pulse height process can take up to 10x slower than the channel extraction process. @jranek that's a good idea, I can see if this will work.

**Comment by ngreenwald** [comment]
Does the channel extraction not have this for loop? That's what I'm confused about, I thought the code for the two processes was similar

**Comment by alex-l-kong** [comment]
It does, but the image extraction loop only gets called once per FOV, extracting the entire image data during the process. However, during the pulse height data generation, the loop gets called multiple times for each channel (specifically, by `write_mph_per_mass` in https://github.com/angelolab/toffy/blob/main/src/toffy/normalize.py#L71-L73).

**Comment by ngreenwald** [comment]
Okay got it
