### ISSUE TITLE
Dockerfile is missing in the main repository - docker build fails and it is not possible to reach the jupyter notebooks

### ISSUE THREAD

**Issue by hillygold** [angelolab/mibi-bin-tools#59]
Dockerfile is missing in the main repository - docker build fails and it is not possible to reach the jupyter notebooks

**Comment by srivarra** [comment]
@hillygold Hello, we removed the docker image as the package can be built natively on all OS / CPU platforms. We will adjust the documentation to reflect this.

**Comment by hillygold** [comment]
OK Thanks. Meanwhile, how can i access the extract_bin_files notebook?
Thank you!

**Comment by srivarra** [comment]
@hillygold We suggest to use [toffy](https://github.com/angelolab/toffy) for the extraction. We have a defined pipeline for the process.
