### ISSUE TITLE
Issue building docker container

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/mibi-bin-tools#6]
noahgreenwald~/Documents/Grad_School/Lab/Segmentation_Project/code$ git clone https://github.com/angelolab/mibi-bin-tools.git
Cloning into 'mibi-bin-tools'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 69 (delta 26), reused 57 (delta 17), pack-reused 0
Unpacking objects: 100% (69/69), done.
noahgreenwald~/Documents/Grad_School/Lab/Segmentation_Project/code$ cd mibi-bin-tools/
noahgreenwald~/Documents/Grad_School/Lab/Segmentation_Project/code/mibi-bin-tools$ docker build -t mibi-bin-tools .
Sending build context to Docker daemon  240.1kB
Step 1/12 : FROM python:3.8
3.8: Pulling from library/python
5e0b432e8ba9: Pull complete 
a84cfd68b5ce: Pull complete 
e8b8f2315954: Pull complete 
0598fa43a7e7: Pull complete 
83098237b6d3: Pull complete 
b92c73d4de9a: Pull complete 
ef9b6ee59783: Pull complete 
c1f6285e6406: Pull complete 
a0ee73333012: Pull complete 
Digest: sha256:881e0df149c29af8b29a973a9e80814dae6cddf123fe38a0bcac71864c85fb8a
Status: Downloaded newer image for python:3.8
 ---> f746089c9d02
Step 2/12 : RUN apt-get update && apt-get install -y gcc
 ---> Running in 7994cfec76bf
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Err:1 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Get:2 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Err:2 http://deb.debian.org/debian bullseye-updates InRelease
  At least one invalid signature was encountered.
Get:3 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Err:3 http://security.debian.org/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
The command '/bin/sh -c apt-get update && apt-get install -y gcc' returned a non-zero code: 100

**Comment by ackagel** [comment]
apparently that error can happen if you run out of build cache space.  you can try clearing it with `docker builder prune`, although that might clear other container build caches as well

**Comment by ngreenwald** [comment]
yup, that did the trick
![image](https://user-images.githubusercontent.com/13770365/145494006-0e45b6cd-4e3f-4ff8-91b6-6afb05be7d6f.png)

**Comment by ngreenwald** [comment]
I get a permission denied error if I try to run the bash script as specified 
![image](https://user-images.githubusercontent.com/13770365/145494602-e0d882c9-c465-433c-8426-19aa747f03a9.png)

**Comment by ngreenwald** [comment]
If i do `bash start_docker.sh` it works fine once I add the -m flag

**Comment by ngreenwald** [comment]
The example jupyter notebook could use a little TLC

**Comment by ackagel** [comment]
`a.ipynb` is doing his best (but yeah, I need to push the actual demo one still)

**Comment by ackagel** [comment]
also, I can change the specification in the readme to the `bash start_docker` syntax instead, that's easy peasy
